const types = {
	FETCH_TODOS_REQUEST: 'FETCH_TODOS_REQUEST',
	FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
	SET_TODO: 'SET_TODO',
	SAVE_TODO_REQUEST: 'SAVE_TODO_REQUEST',
	SAVE_TODO_SUCCESS: 'SAVE_TODO_SUCCESS',
	DELETE_TODO_REQUEST: 'DELETE_TODO_REQUEST',
	DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
};

export default types;
